<a href="https://colab.research.google.com/github/Hannibal730/inflearn_Pytorch/blob/main/1%EA%B0%95_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 텐서

텐서(Tensor)는 파이토치의 기본 단위이며 GPU 연산을 가능하게 한다. 또한 Numpy의 배열과 유사하여 손쉽게 다룰 수 있다.

## 1.1 텐서 만들기

In [1]:
# 라이브러리 불러오기
import torch # Pytorch를 사용하기 위한 기본 라이브러리다.
import numpy as np # Numpy를 사용하기 위한 기본 라이브러리다. 여기서 "as np"는 numpy를 np로 짧게 표기하겠다는 뜻이다.

In [2]:
# 빈 텐서 생성
x = torch.empty(5,4) # 5x4 행렬 생성
print(x) # 초기화되지 않은 행렬인 경우 해당 시점에 할당된 메모리에 존재하던 값들이 초기값으로 나타난다.

tensor([[2.0596e-19, 1.8319e+25, 4.5448e+30, 2.6800e+20],
        [1.8470e+31, 4.6304e+27, 1.7863e+25, 3.7393e-14],
        [2.7255e+20, 1.8467e+20, 7.3881e+31, 3.0356e+32],
        [4.9639e+28, 2.1127e-19, 1.2708e+31, 5.0850e+31],
        [4.2016e+30, 3.2532e+33, 1.1478e-32, 1.3563e-19]])


In [3]:
torch.ones(3,3) # 3x3 일 행렬

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
torch.zeros(2) # 2행 영 벡터

tensor([0., 0.])

In [5]:
torch.rand(5,6) # 5x6 랜덤 행렬

tensor([[0.0184, 0.8074, 0.0450, 0.0912, 0.0976, 0.2968],
        [0.8574, 0.6665, 0.0598, 0.9036, 0.9514, 0.1255],
        [0.2446, 0.2634, 0.0964, 0.3592, 0.0321, 0.1964],
        [0.9225, 0.2863, 0.2132, 0.7759, 0.3166, 0.1462],
        [0.3636, 0.9485, 0.9472, 0.3932, 0.5068, 0.2459]])

## 1.2 리스트, 넘파이 배열을 텐서로 만들기

In [6]:
l = [13,4] # 리스트 생성
r = np.array([4,56,7]) # 넘파이 배열 생성

In [7]:
torch.tensor(l) # 리스트를 텐서로 쉽게 변환할 수 있다.

tensor([13,  4])

In [8]:
torch.tensor(r) #넘파이 배열을 텐서로 쉽게 변환할 수 있다.

tensor([ 4, 56,  7])

In [9]:
torch.FloatTensor(r)

tensor([ 4., 56.,  7.])

## 1.3 텐서의 크기와 타입 확인하기

In [ ]:
x.size()

torch.Size([5, 4])

In [ ]:
x.shape

torch.Size([5, 4])

In [10]:
x.size()[1] # .size()는 텐서의 크기를 확인할 수 있으며 매우 자주 사용된다.

4

In [11]:
type(x) # type은 Python에서 사용되는 모든 것들을 종류를 보여준다.

torch.Tensor

## 1.4 텐서의 덧셈

In [12]:
x = torch.rand(2,2) # 2x2 랜덤 행렬
y = torch.rand(2,2) # 2x2 랜덤 행렬
print(x)
print(y)

tensor([[0.4077, 0.9716],
        [0.1015, 0.4615]])
tensor([[0.6972, 0.4943],
        [0.4392, 0.9241]])


In [13]:
x+y # 두 텐서의 합

tensor([[1.1049, 1.4659],
        [0.5407, 1.3856]])

In [14]:
torch.add(x,y) # 두 텐서의 합의 또 다른 표현

tensor([[1.1049, 1.4659],
        [0.5407, 1.3856]])

In [15]:
y.add(x) # 두 텐서의 합의 또 다른 표현이지만 이는 y에 x를 더한다는 의미다.

tensor([[1.1049, 1.4659],
        [0.5407, 1.3856]])

In [16]:
print("원래 y: ", y)
y.add_(x)
print("y=y+x: ",y)

# y = y+x
# y.add_는 y에 x를 더한 값을 y에 대체한다.(inplace 방식)

원래 y:  tensor([[0.6972, 0.4943],
        [0.4392, 0.9241]])
y=y+x:  tensor([[1.1049, 1.4659],
        [0.5407, 1.3856]])


## 1.5 텐서의 크기 변환하기

In [17]:
x = torch.rand(8,8) # 8x8 랜덤 행렬
print(x.size())

torch.Size([8, 8])


In [18]:
a = x.view(64) # 크기를 바꿔주는 view 8x8 -> 64
print(a.size())

torch.Size([64])


In [19]:
b = x.view(-1,4,4) # -1은 원래 크기가 되게 하는 값 8x8 -> -1x4x4 즉, 4x4x4이다.
print(b.size())

# 따라서 -1은 원래 크기가 되게 하는 값이 자동으로 지정되기 때문에 한 번만 사용할 수 있다.
# 예를 들어 x.view(-1,-1,4)와 같은 선언은 오류가 난다.

torch.Size([4, 4, 4])


## 1.6 텐서에서 넘파이로 만들기

In [20]:
x = torch.rand(8,8)
y = x.numpy() # .numpy()로 매우 간단하게 넘파이 배열로 만들 수 있다.
print(y)

[[0.9352267  0.36820227 0.02586251 0.686005   0.9973779  0.30574733
  0.7032469  0.380862  ]
 [0.45304728 0.8799511  0.12292355 0.00318772 0.09545481 0.9360523
  0.36333525 0.38211256]
 [0.8050812  0.25339276 0.6536441  0.69637954 0.34779602 0.5550628
  0.26220167 0.8754887 ]
 [0.85279804 0.02530903 0.7681587  0.46149117 0.25784558 0.7480236
  0.0492065  0.557991  ]
 [0.18363059 0.2897504  0.4534229  0.82021505 0.7195755  0.8156853
  0.24653387 0.46960306]
 [0.6598872  0.5473448  0.20755702 0.42843038 0.70743865 0.50957817
  0.08940315 0.3174159 ]
 [0.07710844 0.07841045 0.6422284  0.6029124  0.5007533  0.46375066
  0.2761832  0.4893422 ]
 [0.4397719  0.10435015 0.9016447  0.9568851  0.26371938 0.2891
  0.6844308  0.17594928]]


In [21]:
type(y)

numpy.ndarray

## 1.7 단일 텐서에서 값으로 뽑아내기

In [22]:
loss = torch.ones(1)

In [23]:
print(loss)
print(loss.item()) # .item()은 손실 함숫값과 같이 숫자가 하나인 텐서를 텐서가 아닌 값으로 만들어 준다.

tensor([1.])
1.0
