# 1강. 타입, 라이브러리

파이썬(Python)은 데이터 분석 분야에서 매우 널리 쓰이는 프로그래밍 언어 중 하나다. 머신러닝, 딥러닝에 관련 된 라이브러리가 매우 많고 적용이 쉽기 때문이다.

In [ ]:
# 파이썬 버전 체크
!python --version

Python 3.9.16


## 1.1 타입
타입은 모든 프로그래밍 언어에서 가장 중요한 개념이자 기본이다. 또한 타입에 따라 성질이 다르기 때문에 항상 조심해야 하는 부분이다. 우리가 사용하는 모든  것들은 특정 타입을 가지고 있다. 예를 들어 정수형, 실수형, 문자형, 리스트, 배열 등이 있는데 우리가 만든 연산에서 타입 맞지 않으면 원하는 결과를 얻을 수 없다.

In [ ]:
# 원하는 값을 출력하기
print("DeepLearning Bro!")

DeepLearning Bro!


### 1.1.1 int

In [ ]:
# 정수형(int)
a = 1
b = 0
c = -1

In [ ]:
# 타입 확인하기
print(a, type(a))
print(b, type(b))
print(c, type(c))

1 <class 'int'>
0 <class 'int'>
-1 <class 'int'>


In [ ]:
# a+b 표현하기
d = a+b
print(d)

1


In [ ]:
print(a+b)

1


### 1.1.2 float

In [ ]:
# 실수형(float)
a = 1.2
b = 2.4
c = .5

In [ ]:
# 부동 소수점의 문제
print(a+b)

3.5999999999999996


In [ ]:
# 타입 확인하기
print(a, type(a))
print(b, type(b))
print(c, type(c))

1.2 <class 'float'>
2.4 <class 'float'>
0.5 <class 'float'>


### 1.1.3 str

In [ ]:
# 문자형(string)
a = 'deep ' # 'deep'
b = 'learning'
print(type(a),type(b))

<class 'str'> <class 'str'>


In [ ]:
# str의 덧셈
print(a+b) # 문자를 붙여주는 역할

# str은 사칙연산 중 덧셈 연산만 가능하다.

deep learning


### 1.1.4 bool

In [ ]:
# True and False
a = True
b = False
print(type(a),type(b))

<class 'bool'> <class 'bool'>


### 1.1.5 주의하기

In [ ]:
# 숫자형 문자
a = 1
b = '1'
print(a)
print(b)

1
1


In [ ]:
# 간혹 데이터에 숫자처럼 보이지만 문자인 경우들이 있다. 오류에 당황하지 말고 타입을 살펴본다.
print(type(a),type(b))

<class 'int'> <class 'str'>


In [ ]:
# str을 int로 변환하기
c = int(b)
print(c, type(c))

1 <class 'int'>


### 1.1.6 리스트

In [ ]:
# list
list1 = [1,2,3,4]
print(list1, type(list1))

[1, 2, 3, 4] <class 'list'>


In [ ]:
# element
print(list1[0])
print(list1[1])
print(list1[-1])
print(list1[-2])
print(list1[:2])
print(list1[1:3])

1
2
4
3
[1, 2]
[2, 3]


### 1.1.7 튜플

In [ ]:
# tuple
a = (1,2)
print(a, type(a))
print(a[0])
print(a[1])

(1, 2) <class 'tuple'>
1
2


### 1.1.8 딕셔너리

In [ ]:
# dict
a = {"class": ['deep learning', 'machine learning'], "students": [40, 20]}
print(a)

{'class': ['deep learning', 'machine learning'], 'students': [40, 20]}


In [ ]:
print(type(a))

<class 'dict'>


In [ ]:
print(a["class"])

['deep learning', 'machine learning']


In [ ]:
print(a["students"])

[40, 20]


In [ ]:
print(a["students"][0])

40


In [ ]:
# 딕셔너리는 key와 value로 이루어져 있는 모임이다.
# 딕셔너리의 특정 항목만 불러오고 싶은 경우에는 key를 이용한다.
# 위 예시에서는 "class"와 "students"라는 key를 가지고 있다.

a.keys() # 딕셔너리의 모든 keys를 확인할 수 있다.

dict_keys(['class', 'students'])

### 1.1.9 Numpy 배열

In [ ]:
import numpy # numpy 라이브러리 불러오기

arr = numpy.array([1,2,3,4])
print(arr, type(arr))

[1 2 3 4] <class 'numpy.ndarray'>


#### 이 밖에 set, Tensor, DataFrame, Series, PIL Image 등 다양한 타입이 존재한다.

## 1.2 라이브러리
import를 통해 미리 만들어 놓은 함수와 클래스를 쉽게 사용할 수 있으며 다양한 라이브러리들이 존재한다.

In [ ]:
# numpy는 다양한 연산들을 제공하며 데이터 분석에 있어 가장 기본이 되는 라이브러리 중 하나다.

import numpy as np # as를 통해서 라이브러리를 약자로 사용할 수 있다.

arr = np.array([1,2,3,4])
print(arr, type(arr))


[1 2 3 4] <class 'numpy.ndarray'>


In [ ]:
# numpy 내 특정 함수만 불러오기
from numpy import array, ones, zeros

a = array([1,2,3,4])
b = ones(5)
c = zeros((5,2))

In [ ]:
print(a)
print(b)
print(c)

[1 2 3 4]
[1. 1. 1. 1. 1.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
